# Generated by Django 3.0.7 on 2020-06-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=512)),
                ('rate', models.FloatField(default=0)),
                ('thumbnail', models.URLField(default='/static/admin/img/icon-unknown.svg')),
                ('img', models.URLField(default='/static/admin/img/icon-unknown.svg')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
